# Generated by Django 4.2 on 2025-01-04 17:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
