# Generated by Django 4.2 on 2025-01-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_is_staff_profile_admin_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin_access',
        ),
    ]
