# Generated by Django 4.2 on 2025-01-11 15:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_admin_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='../default_profile_hcui3f', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='images/'),
        ),
    ]
