# Generated by Django 4.2 on 2024-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='group',
            field=models.CharField(choices=[('Eco-Conscious Approach', 'Eco-Conscious Approach'), ('Membership / Accreditation', 'Membership / Accreditation'), ('Socially Responsible', 'Socially Responsible'), ('Sustainable Production / Materials', 'Sustainable Production / Materials')], max_length=40),
        ),
    ]
