# Generated by Django 4.2 on 2024-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='content',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='reported',
        ),
        migrations.AddField(
            model_name='credential',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
