# Generated by Django 4.2 on 2025-01-11 19:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='../default_logo_keaza8', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='images/'),
        ),
    ]
