# Generated by Django 4.2 on 2024-12-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsement',
            name='company',
        ),
    ]
