# Generated by Django 4.2 on 2024-12-12 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_alter_company_credentials'),
        ('endorsements', '0002_remove_endorsement_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endorsement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='endorsed_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_company', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsing_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='endorsement',
            unique_together={('owner', 'endorsed_company')},
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='endorsed',
        ),
    ]
